image: php:8.4-cli

stages:
  - validate
  - qa

variables:
  COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.composer-cache"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/
    - .composer-cache/

before_script:
  - apt-get update
  - apt-get install -y git unzip libzip-dev
  - docker-php-ext-install zip
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
  - composer install --no-interaction --no-progress --prefer-dist

validate:composer:
  stage: validate
  script:
    - composer validate --strict

qa:package:
  stage: qa
  script:
    - composer analyze
    - composer sniff
    - composer cs
    - composer test
